Feature: re-add select a different company option
impress-org/give-double-the-donation pull request #22
Opened 2024-08-14 12:10 UTC by alaca

Resolves: [GIVE-1084]

## Description
This PR re-adds the option to select a different company.

## Affects

DTD v3 form block.

## Visuals

https://github.com/user-attachments/assets/cf6e51a2-f939-4c48-8455-3971cb2c9547

## Testing Instructions

Install DTD
Create a new v3 form
Add DTD block
View form on the frontend
Select company
Select another company

## Pre-review Checklist

-   [x] [Self Review](https://give.gitbook.io/development-manual/devops/github/code-reviews#self-review) of code and UX completed

[GIVE-1083]: https://stellarwp.atlassian.net/browse/GIVE-1083?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[GIVE-1084]: https://stellarwp.atlassian.net/browse/GIVE-1084?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2024-08-16 17:13 UTC, pauloiankoski commented
@jdghinson could you review the video here? Are you okay with that "jump" in the label once a company is selected or would you rather have labels static, only replacing the input with the text?

2024-08-17 14:09 UTC, jdghinson commented
@pauloiankoski Let's maintain the label size and if possible change the dropdown icon.

2024-08-22 01:09 UTC, pauloiankoski requested changes
@alaca Let's adjust the styles here (mainly the label and spacings) as they are not matching with the content existing before selecting a company and that causes a little movement in the elements.

2024-08-26 07:42 UTC, alaca commented
@pauloiankoski resolved https://github.com/impress-org/give-double-the-donation/pull/22/commits/291e0b3200a1e54629a04fc8812471d6ffeda6e8

2024-08-26 20:12 UTC, pauloiankoski approved these changes
Seems fine by me. Can we send this to Jeffrey for a Design Review? Once approved then we are ready for QA.

2024-09-03 18:23 UTC, rickalday approved these changes
Passed manual QA tests.

2024-09-03 20:55 UTC, merged